apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.namespace.label }}
    # tag: alpine
  name: {{ .Values.namespace.label }}
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: {{ .Values.service.protocol }}
    targetPort: {{ .Values.service.targetPort }} 
  selector:
    app: {{ .Values.namespace.label }}
    # tag: alpine
  type: {{ .Values.service.specType }}
