namespace:
  name: sandbox
  label: techtrends

replicaCount: 1

containerPort: 3111

image:
  repository: jdhaines/techtrends
  tag: latest
  pullPolicy: IfNotPresent

resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"

livenessProbe:
  path: /healthz
  port: 3111

readinessProbe:
  path: /healthz
  port: 3111

service:
  port: 4111
  protocol: TCP
  targetPort: 3111
  specType: ClusterIP